#!/usr/bin/env python3

import json
import pprint
import pandas as pd

from sklearn.linear_model import LinearRegression
from joblib import dump, load
from os import listdir

PATHS = {
    'hyperparameters': 'input/config/hyperparameters.json',
    'input': 'input/config/inputdataconfig.json',
    'data': 'input/data/',
    'model': 'model/'
}


def get_path(key):
    return '/opt/ml/' + PATHS[key]


def load_json(target_file):
    output = None
    
    with open(target_file) as json_data:
        output = json.load(json_data)

    return output


def print_json(target_json):
    pprint.pprint(target_json, indent=4)


def inspect_hyperparameters():
    print('[inspect_hyperparameters]')
    hyperparameters_json_path = get_path('hyperparameters')
    print(hyperparameters_json_path)
    
    hyperparameters = load_json(hyperparameters_json_path)
    print_json(hyperparameters)
    
    
def list_dir_contents(target_path):
    print('[list_dir_contents]')
    
    output = listdir(target_path)
    print(output)
    
    return output


def inspect_input():
    print('[inspect_input]')
    input_config_json_path = get_path('input')
    print(input_config_json_path)
    
    input_config = load_json(input_config_json_path)
    print_json(input_config)
    
    
def load_training_data(input_data_dir):
    print('[load_training_data]')
    
    files = list_dir_contents(input_data_dir)
    training_data_path = input_data_dir + files[0]
    print(training_data_path)
    
    df = pd.read_csv(training_data_path, header=None)
    print(df)
    
    y_train = df[0].values
    X_train = df[1].values
    
    return (X_train, y_train)
    
    
def get_input_data_dir():
    print('[get_input_data_dir]')
    key = 'train'
    input_data_dir = get_path('data') + key + '/'
    
    return input_data_dir


def train_model(X_train, y_train):
    print('[train_model]')
    model = LinearRegression()
    model.fit(X_train.reshape(-1, 1), y_train)
    
    return model


def save_model(model):
    print('[save_model]')
    filename = get_path('model') + 'model'
    print(filename)
    dump(model, filename)
    
    print('Model Saved!')


def main():
    inspect_hyperparameters()
    inspect_input()
    
    input_data_dir = get_input_data_dir()
    X_train, y_train = load_training_data(input_data_dir)
    model = train_model(X_train, y_train)
    save_model(model)
    
    
if __name__ == "__main__":
    main()
